
variables:
  SYSTEM: slc6
  NAME: gitlab-registry.cern.ch/swan/docker-images/systemuser


stages:
    - build
    - test
    - deploy
    - clean


build_image:
    stage: build
    script: docker build --compress --rm -t $CI_COMMIT_SHA .
    except:
        - web
        - master


test_all:
    stage: test
    script: python3 /tests/test_image.py --image $CI_COMMIT_SHA --system $SYSTEM
    only: 
        - /^v.*$/
    except:
        - web
    when: on_success


test_latest:
    stage: test
    script: python3 /tests/test_image.py --image $CI_COMMIT_SHA --stack latest --system $SYSTEM
    except: 
        - tags
        - master
    when: on_success


test_release:
    stage: test
    script: python3 /tests/test_image.py --image latest:$SYSTEM --system $SYSTEM --stack $STACK --platform $PLATFORM --python $PYTHON
    only: 
        - web


publish_image:
    stage: deploy
    script:
        - docker tag $CI_COMMIT_SHA latest:$SYSTEM
        - docker tag $CI_COMMIT_SHA $NAME:$CI_COMMIT_TAG
        - docker login gitlab-registry.cern.ch -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $NAME:$CI_COMMIT_TAG
        - docker logout
    only: 
        - /^v.*$/
    except:
        - web
    when: on_success


clean_images:
    stage: clean
    script:
        - docker rmi $CI_COMMIT_SHA
    except: 
        - master
        - web
